# Generated by Django 5.2.7 on 2025-10-31 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_name_39f70b_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_is_acti_7db955_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_title_c91890_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_is_acti_14fc6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_price_2d2a4c_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=230, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
